#!/bin/bash
#set -x

export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

echo "<html>"
cat << _END_
<head>
<title>Virtualization status</title>
<style type="text/css">
body {color: black; background: white; }
th {color: white; background: black; text-align: left; }
table {border-collapse: collapse; }
td {border-bottom: #eee solid 1px; vertical-align: top; }
.column1 {width: 20em; }
.column2 {width: 8em; }
.column3 {width: 8em; }
.column4 {width: 8em; }
table {width: 100%; margin-left: auto; margin-right: auto; }
.footer {text-align: right; margin-top: 20px; font-size: 0.8em; }
</style>
</head>
_END_

echo "<body>"
echo "<h1> Virtualization status</h1>"
echo "<h2>VServer</h2>"
echo "<table>"
echo "<tr><th class=\"column1\">name</th><th class=\"column2\">status</th><th class=\"column3\">memory</th><th class=\"column4\">autostart</th><th>description </th></tr>"
for vs in `ls /etc/vservers/ | egrep -v '(run.sh|TEMPLATE)' ` ; do vserver $vs status; done | grep Vserver | awk '{print $2 " " $4}' | tr -d "'" | while read line
do
	vs=$(echo "$line" | cut -d " " -f 1)
	line="$(echo "$line" | sed -e "s# #|#g" )|($(vserver-stat | grep " $vs$" | awk '{print $3}'))|$( if grep -q default /etc/vservers/$vs/apps/init/mark 2>/dev/null ; then echo "yes" ; fi )|$(grep "^vserver:$vs:" /etc/virtstatus/descriptions | cut -d : -f 3-)"
	echo "$line" | sed -e 's#^#<tr><td>#g' -e 's#|#</td><td>#g' -e 's#$#</td></tr>#g' | sed -e 's#stopped#<span style="color: red">stopped</span>#g'  -e 's#running#<span style="color: green">running</span>#g'
done
echo "</table>"

echo "<h2>Xen</h2>"
echo "<table>"
echo "<tr><th class=\"column1\">name</th><th class=\"column2\">status</th><th class=\"column3\">memory</th><th class=\"column4\">autostart</th><th>description </th></tr>"
for vs in `ls /etc/xen/ | grep '.cfg' |sed -e "s#\.cfg##" `
do
	echo -n "<tr><td>$vs</td>"
	echo -n "<td>"
	if xm list "$vs" &> /dev/null
	then
		echo -n '<span style="color: green">running</span>'
	else
		echo -n '<span style="color: red">stopped</span>'
	fi	
	echo -n '</td>'
	echo -n '<td>'
	grep "^memory = " /etc/xen/$vs.cfg | cut -d = -f 2-
	echo -n '</td>'
	echo -n '<td>'
	if test -f /etc/xen/auto/$vs.cfg 2>/dev/null
	then
		echo "yes"
	fi
	echo -n '</td>'
	echo -n '<td>'
	grep "^xen:$vs:" /etc/virtstatus/descriptions | cut -d : -f 3-
	echo -n '</td>'
	echo '</tr>'
done
echo "</table>"

echo "<h2>KVM</h2>"
echo "<table>"
echo "<tr><th class=\"column1\">name</th><th class=\"column2\">status</th><th class=\"column3\">memory</th><th class=\"column4\">autostart</th><th>bridge</th><th>description </th></tr>"
virsh list --all | tail -n +3 | awk '{print $2}' | while read i ; do  if virsh dumpxml $i 2>/dev/null | grep -q '<domain type=.kvm.' ; then echo $i ; fi ; done | while read line
do
	vs=$(echo "$line" | cut -d " " -f 1)
	echo -n "<tr><td>$vs</td>"
	echo -n "<td>"
	if virsh domstate "$vs" | grep -q running &> /dev/null
	then
		echo -n '<span style="color: green">running</span>'
	else
		echo -n '<span style="color: red">stopped</span>'
	fi	
	echo -n '</td>'
	echo -n '<td>'
	mem_line=""
	mem_line=$(virsh dominfo $vs | grep "^Max memory:" | cut -d : -f 2-)
	if echo "$mem_line" | grep -q kB
	then
		echo $mem_line | while read a b ; do echo "$(( $a / 1024 )) MB" ; done
	else
		echo "$mem_line"
	fi
	echo -n '</td>'
	echo -n '<td>'
	#if test -f /etc/xen/auto/$vs.cfg 2>/dev/null
	#virsh dominfo merc.etn | grep "^Autostart:" | cut -d : -f 2-
	#echo "unknown"
	#then
	#	echo "yes"
	#fi
	if [ -s /etc/libvirt/qemu/autostart/$vs.xml ] ; then
		echo enabled
	fi
	echo -n '</td>'

	echo -n '<td>'
	virsh dumpxml $vs | grep bridge= | cut -d "'" -f 2
	echo -n '</td>'

	echo -n '<td>'
	grep "^kvm:$vs:" /etc/virtstatus/descriptions | cut -d : -f 3-
	echo -n '</td>'
	echo '</tr>'

	#line="$(echo "$line" | sed -e "s# #|#g" )|($(vserver-stat | grep " $vs$" | awk '{print $3}'))|$( if grep -q default /etc/vservers/$vs/apps/init/mark 2>/dev/null ; then echo "yes" ; fi )|$(grep "^vserver:$vs:" /etc/virtstatus/descriptions | cut -d : -f 3-)"
	#line="$vs|unknown|unknown|unknown|$(grep "^kvm:$vs:" /etc/virtstatus/descriptions | cut -d : -f 3-)"
	#echo "$line" | sed -e 's#^#<tr><td>#g' -e 's#|#</td><td>#g' -e 's#$#</td></tr>#g' | sed -e 's#stopped#<span style="color: red">stopped</span>#g'  -e 's#running#<span style="color: green">running</span>#g'
done
echo "</table>"

echo "<h2>Notes</h2>"
echo "<p>Description je ziskavano z /etc/virtstatus/descriptions</p>"
echo "<div class=\"footer\"><tr>Generated: $(date)</div>"
echo "</html>"
